=== lde-org/registry/schemas/index.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "array",
	"items": {
		"type": "object",
		"required": ["name", "git", "latest"],
		"properties": {
			"name": {
				"type": "string"
			},
			"description": {
				"type": ["string", "null"]
			},
			"authors": {
				"type": "array",
				"items": { "type": "string" }
			},
			"latest": {
				"type": ["string", "null"]
			},
			"git": {
				"type": "string",
				"format": "uri"
			},
			"lastUpdated": {
				"type": ["string", "null"],
				"format": "date-time",
				"description": "When a new version was last added to this package."
			},
			"firstPublished": {
				"type": ["string", "null"],
				"format": "date-time",
				"description": "When this package was first published to the registry."
			},
			"approximate": {
				"const": true,
				"description": "Set when the dates were reconstructed from registry history and are estimates."
			}
		},
		"additionalProperties": false
	}
}

=== lde-org/registry/index.json
[{"name":"tltp/mail","description":"SMTP client addon for tltp","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.3.3","git":"https://codeberg.org/kmafeni04/tltp.git","lastUpdated":"2026-10-21T00:57:34Z","firstPublished":"2026-09-08T20:09:47Z","approximate":true},{"name":"tltp","description":"A Teal/LuaJIT HTTP/1.1 web server library","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.3.3","git":"https://codeberg.org/kmafeni04/tltp.git","lastUpdated":"2026-10-21T00:56:08Z","firstPublished":"2026-09-02T15:34:35Z","approximate":true},{"name":"fstrings","description":"Adding string interpolation to lua","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.2.0","git":"https://codeberg.org/kmafeni04/fstrings-lua.git","lastUpdated":"2026-10-19T22:21:26Z","firstPublished":"2026-08-16T12:23:21Z","approximate":true},{"name":"targs","description":"A command line argument parser for lua and teal","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.5.0","git":"https://codeberg.org/kmafeni04/targs.git","lastUpdated":"2026-10-19T20:53:49Z","firstPublished":"2026-08-14T16:28:51Z","approximate":true},{"name":"tmcp","description":"An MCP server runtime for Teal with stdio and Streamable HTTP transports","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.1.0","git":"https://codeberg.org/kmafeni04/tmcp.git","lastUpdated":"2026-10-12T02:07:59Z","firstPublished":"2026-10-12T02:07:59Z"},{"name":"lua-sys","description":"LuaJIT C api bindings for lde.","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.5","git":"https://github.com/lde-org/lua-sys.git","lastUpdated":"2026-10-11T20:57:52Z","firstPublished":"2026-08-16T05:21:05Z","approximate":true},{"name":"json","description":"JSON(5) encoding and decoding for lde, backed by yyjson.","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.1","git":"https://github.com/lde-org/json.git","lastUpdated":"2026-10-11T18:18:07Z","firstPublished":"2026-09-10T07:39:47Z","approximate":true},{"name":"fs","description":"A cross platform fs library for lde.","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.3.0","git":"https://github.com/lde-org/fs.git","lastUpdated":"2026-10-11T08:28:19Z","firstPublished":"2026-08-16T04:51:41Z","approximate":true},{"name":"curl-sys","description":"Bindings to curl for lde.","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.2","git":"https://github.com/lde-org/curl-sys.git","lastUpdated":"2026-10-09T06:18:01Z","firstPublished":"2026-08-16T05:25:17Z","approximate":true},{"name":"t","description":"The only table library you will need","authors":["sysfab"],"latest":"1.0.0","git":"https://github.com/sysfab/t.git","lastUpdated":"2026-10-04T09:24:12Z","firstPublished":"2026-10-04T09:24:12Z"},{"name":"process","description":"A cross platform process library for lde.","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.2","git":"https://github.com/lde-org/process.git","lastUpdated":"2026-09-29T18:03:39Z","firstPublished":"2026-08-27T17:33:49Z","approximate":true},{"name":"tlcat","description":"Bidirectional Teal to LuaCATS type-definition compiler","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.2.0","git":"https://codeberg.org/kmafeni04/tlcat.git","lastUpdated":"2026-09-26T22:42:15Z","firstPublished":"2026-09-26T22:42:15Z"},{"name":"ssdg","description":"A language agnostic documentation generator written","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.4.0","git":"https://codeberg.org/kmafeni04/ssdg.git","lastUpdated":"2026-09-26T17:04:58Z","firstPublished":"2026-08-15T13:15:51Z","approximate":true},{"name":"winapi","description":"Windows API bindings for LuaJIT.","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.3","git":"https://github.com/bycruz/winapi.git","lastUpdated":"2026-09-26T07:19:06Z","firstPublished":"2026-09-17T10:13:26Z","approximate":true},{"name":"hood","description":"Cross platform graphics API for LuaJIT","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.2.8","git":"https://github.com/bycruz/hood.git","lastUpdated":"2026-09-26T06:40:36Z","firstPublished":"2026-03-15T01:10:23Z","approximate":true},{"name":"wonderland","description":"A cross platform UI library for LuaJIT","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.3","git":"https://github.com/bycruz/wonderland.git","lastUpdated":"2026-09-25T16:05:57Z","firstPublished":"2026-09-25T16:05:57Z"},{"name":"texter","description":"Text shaping and glyphs from what the system already has","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.2","git":"https://github.com/bycruz/texter.git","lastUpdated":"2026-09-25T00:37:27Z","firstPublished":"2026-09-25T00:37:27Z"},{"name":"image","description":"Image encoding, decoding and manipulation library","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.3","git":"https://github.com/lde-org/image.git","lastUpdated":"2026-09-24T09:15:25Z","firstPublished":"2026-09-24T09:15:25Z"},{"name":"treble","description":"A cross platform audio library for LuaJIT","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.1","git":"https://github.com/bycruz/treble.git","lastUpdated":"2026-09-23T09:18:51Z","firstPublished":"2026-09-23T09:18:51Z"},{"name":"superfast","description":"An incredibly fast HTTP server in pure LuaJIT","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.1","git":"https://github.com/bycruz/superfast.git","lastUpdated":"2026-09-21T20:46:22Z","firstPublished":"2026-09-21T20:46:22Z"},{"name":"env","description":"A cross platform env library for lde","authors":["David Cruz <david@bycruz.dev"],"latest":"0.1.1","git":"https://github.com/lde-org/env.git","lastUpdated":"2026-09-19T17:22:45Z","firstPublished":"2026-09-17T10:07:07Z","approximate":true},{"name":"html","description":"A html DSL written for lua and teal","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.3.0","git":"https://codeberg.org/kmafeni04/html-lua.git","lastUpdated":"2026-09-18T12:10:38Z","firstPublished":"2026-08-17T10:28:27Z","approximate":true},{"name":"lupa","description":"A 2d/3d game creation framework for LuaJIT","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.1","git":"https://github.com/bycruz/lupa.git","lastUpdated":"2026-09-17T20:26:21Z","firstPublished":"2026-09-17T20:26:21Z"},{"name":"winit","description":"Cross platform windowing library for LuaJIT","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.7","git":"https://github.com/bycruz/winit.git","lastUpdated":"2026-09-17T11:42:47Z","firstPublished":"2026-09-17T11:42:47Z"},{"name":"glapi","description":"OpenGL api bindings for LuaJIT","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.1","git":"https://github.com/bycruz/glapi.git","lastUpdated":"2026-09-17T11:35:56Z","firstPublished":"2026-09-17T11:35:56Z"},{"name":"x11api","description":"X11 api bindings for LuaJIT","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.2","git":"https://github.com/bycruz/x11api.git","lastUpdated":"2026-09-17T11:34:08Z","firstPublished":"2026-09-17T11:34:08Z"},{"name":"vkapi","description":"Cross Platform Vulkan API bindings for LuaJIT","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.2","git":"https://github.com/bycruz/vkapi.git","lastUpdated":"2026-09-17T11:30:12Z","firstPublished":"2026-09-17T11:30:12Z"},{"name":"git2-sys","description":"Bindings to git2 for lde.","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.2.0","git":"https://github.com/lde-org/git2-sys.git","lastUpdated":"2026-09-17T10:18:42Z","firstPublished":"2026-08-16T05:19:31Z","approximate":true},{"name":"clap","description":"A minimal, lazy command line argument parser","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.0","git":"https://github.com/lde-org/clap.git","lastUpdated":"2026-09-17T10:02:17Z","firstPublished":"2026-09-17T10:02:17Z","approximate":true},{"name":"rv","description":"An incredibly minimal reverse engineering tool.","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.1.0","git":"https://github.com/bycruz/revolver.git","lastUpdated":"2026-09-17T09:50:36Z","firstPublished":"2026-09-17T09:50:36Z","approximate":true},{"name":"tltp/datastar","description":"Datastar SSE helpers for tltp","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.3.2","git":"https://codeberg.org/kmafeni04/tltp.git","lastUpdated":"2026-09-12T22:45:07Z","firstPublished":"2026-09-08T20:09:20Z","approximate":true},{"name":"socket","description":"A cross platform socket library.","authors":["David Cruz <david@bycruz.dev>"],"latest":"0.3.0","git":"https://github.com/lde-org/socket.git","lastUpdated":"2026-09-07T20:30:30Z","firstPublished":"2026-09-04T05:15:01Z","approximate":true},{"name":"kmafeni04/dotenv","description":"A .env file parser for Teal/Lua","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.1.0","git":"https://codeberg.org/kmafeni04/dotenv-lua.git","lastUpdated":"2026-09-03T13:25:38Z","firstPublished":"2026-09-03T13:25:38Z","approximate":true},{"name":"sstream","description":"A library to compose strings","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.1.5","git":"https://codeberg.org/kmafeni04/sstream-lua.git","lastUpdated":"2026-09-03T11:55:03Z","firstPublished":"2026-08-15T13:16:26Z","approximate":true},{"name":"ansicolor","description":"Color text using ansi escape sequences","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.4.0","git":"https://codeberg.org/kmafeni04/ansicolor-lua.git","lastUpdated":"2026-08-30T20:13:42Z","firstPublished":"2026-08-16T12:25:14Z","approximate":true},{"name":"tlrm","description":"A Teal/Lua ORM","authors":["Leonard Mafeni <komemafeni944@gmail.com>"],"latest":"0.1.0","git":"https://codeberg.org/kmafeni04/tlrm.git","lastUpdated":"2026-08-26T18:20:14Z","firstPublished":"2026-08-26T18:20:14Z","approximate":true},{"name":"inflect","description":"A string inflection library for lua/teal","authors":["Leonard Mafeni <komemafeni944@gmail.com
